project:
  type: default
  output-dir: final_html
  pre-render: scripts/my_env.py

format:
  html:
    css: styles.css
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 2
    embed-resources: true

execute:
  echo: true
  warning: false
  message: false

jupyter: python3